### ISSUE TITLE
支持 adb

### ISSUE THREAD

**Issue by NateScarlet** [NateScarlet/auto-derby#44]
from #42 

adb和模拟器没法指定分辨率 模版匹配难度会提升

**Comment by fatinghenji** [comment]
不是很有道理(~但是很容易~)的解决方案：
电脑的模拟器和安卓虚拟机都可以手动设定分辨率和dpi，直接让用户按规定的分辨率和dpi使用。
~隔壁方舟的托管就是这样解决的~

**Comment by NateScarlet** [comment]
现在的截图用的不是标准大小 而是 466 x 828 需要把所有数据都改成适配 540 x 960 的

这个分辨率是从它默认的窗口大小提取出来了的，然后我发现它默认大小好像每次都不一样

**Comment by NateScarlet** [comment]
然后我自己不能用 540 x 960 因为我副屏放三行的任务栏 剩余空间没有 960 那么高

**Comment by fatinghenji** [comment]
> 现在的截图用的不是标准大小 而是 466 x 828 需要把所有数据都改成适配 540 x 960 的

好家伙，那工作量确实好大

> 这个分辨率是从它默认的窗口大小提取出来的，然后我发现它默认大小好像每次都不一样

？还有这种奇怪的事情？

**Comment by NateScarlet** [comment]
不过增大分辨率也有好处就是OCR更难出错 如果能实现后台挂机那我也不需要放副屏了

**Comment by fatinghenji** [comment]
> 现在的截图用的不是标准大小 而是 466 x 828 

vmos那个安卓手机端的虚拟机支持非标准大小。
![image](https://user-images.githubusercontent.com/37131177/121818930-e43c3100-ccbc-11eb-8bdf-869152fc5cf5.png)
~不过我真没想到会这么糊~

**Comment by NateScarlet** [comment]
我在把坐标都改成相对窗口宽度的了 0b530446422134b05f75283e8ae4314a90a89154

然后后面再加上识图的时候统一缩放成 540x960 的 看精确度咋样

**Comment by fatinghenji** [comment]
好诶！可以放出一个测试版吗？一会到家了可以试试

**Comment by NateScarlet** [comment]
还没加呢 现在重构就是方便新写的功能不需要后面重新适配

**Comment by fatinghenji** [comment]
辛苦作者了！我是个只会提需求的笨比

**Comment by Splendent** [comment]
如果能支援模擬器ADB那真是幫了大忙了，畢竟在WINDWOS上用VPN有太多不便，DMM GAMES本身程式又擋vm，我身邊兩三個同事也是有相同需求；
更新這麼勤奮必須給個star⭐！ 👍

**Comment by NateScarlet** [comment]
开发分支已经改成用 540x960 了 改了之后所有育成事件都要重新选

模版我是全部整体放大的 跑了一次育成发现非文本模版大多都能直接用

等所有功能都用过一遍再放到 master

**Comment by NateScarlet** [comment]
我在模拟器上装了测试了 发现模拟器窗口也不能后台点击 估计游戏不处理 windows 的点击消息

只能模拟器也通过 adb 来操作

**Comment by fatinghenji** [comment]
对哇，模拟器也需要通过adb
```
device:
  # ADB server 的端口。部分模拟器为避免冲突可能会将 ADB server 开在其他端口，
  # 此时可以更改此设置以利用模拟器自带的 ADB server。
  # adb_server: 127.0.0.1:5037

  # 需要启动 adb server 时，使用的 adb 命令
  # 为空时则尝试: 1. PATH 中的 adb；
  #               2. ADB/{sys.platform}/adb;
  #               3. 查找 Android SDK（ANDROID_SDK_ROOT 和默认安装目录）
  adb_binary:
  # 以下为部分模拟器提供的 adb 程序，不一定正确，仅供参考
  # adb_binary: D:\leidian\LDPlayer\adb.exe             # 雷电模拟器
  # adb_binary: C:\Program Files\BlueStacks\HD-Adb.exe  # BlueStacks
  # adb_binary: C:\Program Files (x86)\MuMu\emulator\nemu\vmonitor\bin\adb_server.exe  # MuMu模拟器

  # 始终选择指定设备进行操作（指定 adb devices 中列出的名称）
  # adb_always_use_device:

  # 无设备连接时进行的操作
  # 如果某个操作报告成功，则不再执行后续定义的操作
  adb_no_device_fixups:
  - run: probe_bluestacks_hyperv  # 自动探测并连接 BlueStacks Hyper-V 的 ADB 端口
  - run: adb_connect  # 连接 ADB TCP/IP 端口
    target:
    - 127.0.0.1:5555    # 大部分模拟器
    - 127.0.0.1:7555    # MuMu模拟器
    try_all: false  # 某个端口连接成功后，是否继续尝试后续定义的端口

  # 使用兼容性较好（但较慢）的截图方式
  compat_screenshot: false

  # 通过 adb 传输模拟器截图数据较慢时，尝试绕过 adbd 传输截图数据
  # 模拟器判断逻辑：1. 设备名称以 "emulator-" 或 "127.0.0.1:" 开头
  #                 2. ro.product.board 包含 goldfish（SDK emulator）或存在 vboxguest 模块
  # 可用选项：never, auto, always
  workaround_slow_emulator_adb: auto

  # 截图缓存：如果两次截图间隔小于上次截图耗时，则直接返回上次的截图
  cache_screenshot: true
```
隔壁[明日方舟护肝助手](https://github.com/ninthDevilHAUNSTER/ArknightsAutoHelper)的config文件，可以参考下
